import { type Character, deriveNormalJaName, deriveTauntJaName, type Move } from '@repo/core'
import overrides from './alias-overrides.json'
// generated/index.ts is auto-generated by apps/scraper (per-character JSON merged into an array).
import generated from './generated'
import saLevels from './sa-levels.json'
import translations from './translations.json'

// Generated data. apps/scraper fetches and normalizes it from the SuperCombo Wiki
// (CC-BY-SA) via cargoquery, then emits JSON validated against core's zod schema.
// Each Move's source records its attribution.
const generatedCharacters = generated as unknown as readonly Character[]

// Manual alias layer. Shape: { [characterId | "all"]: { [input.numpad]: { aliases?, ja? } } }.
// Managed separately from the auto-generated JSON so it survives re-scraping. Universal
// system moves (DI/reversal/parry/rush) are stored under character-specific names, so they
// are applied across all characters via "all", keyed by input (numpad).
// See docs/data-model.md for details.
interface AliasOverride {
  aliases?: string[]
  ja?: string
}
type OverrideMap = Record<string, Record<string, AliasOverride>>

function applyOverride(move: Move, override: AliasOverride): Move {
  const aliases = override.aliases
    ? Array.from(new Set([...move.aliases, ...override.aliases]))
    : move.aliases
  // Respect an existing ja value; only fill in when unset (null).
  const name = override.ja && move.name.ja === null ? { ...move.name, ja: override.ja } : move.name
  return { ...move, aliases, name }
}

// For SA level detection. SA1/SA2/SA3 are not in the source data, so they are
// manually curated in packages/data/src/sa-levels.json (base motion → level). SA3
// aligns with the (CA) marker, but SA1/SA2 require character knowledge.
// See docs/data-model.md for details.
interface SaLevel {
  sa1?: string
  sa2?: string
  sa3?: string
}
type SaLevelMap = Record<string, SaLevel>

// Normalize input to the SA's "bare motion" (strip j./charge[]/(CA)(hold)/+/~derivation/strength).
//   236236LP → 236236P, [4]646HP → 4646P, j.214214P → 214214P, 720+P → 720P
function superBaseMotion(numpad: string): string {
  return numpad
    .replace(/^j\./, '')
    .replace(/\s*\(.*?\)\s*/g, '')
    .replace(/[[\]{}]/g, '')
    .replace(/\+/g, '')
    .replace(/~.*$/, '')
    .replace(/([LMH])([PK])/g, '$2')
    .trim()
}

// Detect aerial SAs solely by the j. prefix on the input.
// This avoids misclassifying ground moves whose name contains "Aerial"
// (e.g. Zangief "Aerial Russian Slam" is the grounded 236236K) as aerial.
function isAerialSuper(move: Move): boolean {
  return move.input.numpad.startsWith('j.')
}

function saLevelOf(base: string, sa: SaLevel): 1 | 2 | 3 | null {
  if (sa.sa1 && base === sa.sa1) return 1
  if (sa.sa2 && base === sa.sa2) return 2
  if (sa.sa3 && base === sa.sa3) return 3
  return null
}

// Generate SA aliases for a super_art (SA1-3 / aerial SA / CA / generic SA).
// Only moves whose motion matches the SA1/2/3 confirmed in sa-levels.json get aliases.
// Non-matching supers (boss versions or derivations, e.g. M.Bison "Final Psycho Crusher" /
// Ingrid "Sun Octopus") are not hit by SA-style queries (still queryable by name/input;
// this prevents confusion from false hits).
// CA (Critical Art) = the low-health enhanced version of a level-3 SA. It shares the input
// with SA3 but has different damage/frames as a separate record ("X" / "X (CA)"), so it gets
// a separate alias: SA3 → normal version, CA → "(CA)" version.
function superArtAliases(move: Move, sa: SaLevel): string[] {
  const isCa = move.name.en.includes('(CA)')
  const level = saLevelOf(superBaseMotion(move.input.numpad), sa)
  // Exclude supers that match no curated SA and are not CA (boss/derived versions,
  // e.g. M.Bison "Final Psycho Crusher").
  // But always register a (CA)-marked move as CA even if it maps to no SA1/2/3
  // (e.g. Akuma's 瞬獄殺 Shun Goku Satsu is a standalone CA whose input matches no SA motion).
  if (level === null && !isCa) {
    return []
  }
  const aerial = isAerialSuper(move)
  const out = aerial ? ['空中SA', '空中スーパーアーツ'] : ['SA', 'スーパーアーツ', 'super']
  if (isCa) {
    out.push('CA', 'クリティカルアーツ', 'critical art')
  } else {
    const prefix = aerial ? '空中' : ''
    out.push(`${prefix}SA${level}`, `${prefix}スーパーアーツ${level}`)
  }
  return out
}

// Manual translation layer for proper-noun moves: { [characterId]: { [move name (en)]: Japanese name } }.
// Curated from official tables. Survives re-scraping (see docs/data-model.md).
// Keys accept both the "full name" (suffix kept) and the "base name" (strength/level/parens stripped).
// Use the base name for moves you want to share across strengths, and the full name for moves
// named differently per variant ("Marisa Style (HK)" etc.). deriveJaName looks up full name → base name.
type TranslationMap = Record<string, Record<string, string>>

// "Full name" with only HTML line-break artifacts removed. Parens/strength/level are kept as-is.
//   "Sweep Combination 1<br>(Flying...)" → "Sweep Combination 1"
//   "Marisa Style (HK)" → "Marisa Style (HK)"
function cleanFullName(nameEn: string): string {
  return nameEn
    .replace(/<br>[\s\S]*$/i, '')
    .replace(/\s+/g, ' ')
    .trim()
}

// Get the base move name with suffixes stripped, for matching translation keys.
//   "Shin Shoryuken (CA)" / "Denjin Hashogeki Lv.1" / "Breakin' ~ Drink" → base name
function baseMoveName(nameEn: string): string {
  return nameEn
    .replace(/<br>.*$/i, '') // drop everything after the source's HTML line-break artifact
    .replace(/\s*\(.*?\)\s*/g, ' ')
    .replace(/\s*Lv\.\d+/gi, '')
    .replace(/\s*~.*$/, '')
    .replace(/^(HP|MP|LP|HK|MK|LK|OD|EX)\s+/, '') // strip strength prefix ("HP Flash Knuckle"→"Flash Knuckle")
    .trim()
}

// Determine the Japanese move name: normals derived from input → taunts derived from name →
// proper nouns from manual translation (look up full name first, then the base name with strength etc. stripped).
function deriveJaName(move: Move, translation: Record<string, string> | undefined): string | null {
  return (
    deriveNormalJaName(move.input.numpad) ??
    deriveTauntJaName(move.name.en) ??
    translation?.[cleanFullName(move.name.en)] ??
    translation?.[baseMoveName(move.name.en)] ??
    null
  )
}

function enrichMove(
  move: Move,
  universal: Record<string, AliasOverride>,
  perCharacter: Record<string, AliasOverride>,
  sa: SaLevel | undefined,
  translation: Record<string, string> | undefined,
): Move {
  let result = move
  // 1. Fill in the Japanese move name (only when ja is unset). Normals/taunts are auto-derived; proper nouns come from the manual translation layer.
  if (result.name.ja === null) {
    const ja = deriveJaName(result, translation)
    if (ja) {
      result = { ...result, name: { ...result.name, ja } }
    }
  }
  // 2. Add SA aliases (SA1-3 / aerial SA / CA / generic) to super_art moves.
  if (result.category === 'super_art' && sa) {
    const saAliases = superArtAliases(result, sa)
    result = { ...result, aliases: Array.from(new Set([...result.aliases, ...saAliases])) }
  }
  // 3. Manual overrides (ja/aliases). Proper nouns and system moves are supplemented by the manual layer (manual wins).
  const universalOverride = universal[move.input.numpad]
  if (universalOverride) {
    result = applyOverride(result, universalOverride)
  }
  const characterOverride = perCharacter[move.input.numpad]
  if (characterOverride) {
    result = applyOverride(result, characterOverride)
  }
  return result
}

function enrich(
  source: readonly Character[],
  overrideMap: OverrideMap,
  saMap: SaLevelMap,
  translationMap: TranslationMap,
): readonly Character[] {
  const universal = overrideMap.all ?? {}
  return source.map((character) => {
    const perCharacter = overrideMap[character.id] ?? {}
    const sa = saMap[character.id]
    const translation = translationMap[character.id]
    return {
      ...character,
      moves: character.moves.map((move) =>
        enrichMove(move, universal, perCharacter, sa, translation),
      ),
    }
  })
}

export const characters: readonly Character[] = enrich(
  generatedCharacters,
  overrides as OverrideMap,
  saLevels as SaLevelMap,
  translations as TranslationMap,
)

export function getCharacters(): readonly Character[] {
  return characters
}

// Identifier for the generated snapshot (fetch date)
export const dataVersion = '2026-06-15'
